version: '3.8'

services:
  movie-box-office:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - PORT=${PORT:-3000}
      - API_BASE_URL=${API_BASE_URL}
      - TMDB_API_KEY=${TMDB_API_KEY}
    restart: unless-stopped